version: '3.3'

services:
  tracker:
    build: ./
    ports:
      - "8080:8080"
      - "8081:8081/udp"
    environment:
      - TRACKER_PORT=8080
      - TRACKER_UDP_PORT=8081
      - MONGO_URI=mongodb://mongo:27017
      - ALLOWED_IPS=127.0.0.1
      - BLOCKED_IPS=192.168.1.1
      - RATE_LIMIT=600
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
